server:
  port: 8080

spring:
  application:
    name: jiplink
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: ENC(sRG1eoUBYY2o9jOtbD4oRU1rijUGl9Nr2UNk7oQo2LFAQi1cVLV5pP/ZwBn8UUtBG53DN70tbOg7vC3/hMLZ7AAtBregCU4jwwfIFrbyGerpBb93gOJI/lZAqrxqD7QRtCkENqcgxgx9ws8NTLrMojEjI9ILo7CN221koVIeGLw=)
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: ENC(9LKLokyoaUAQRonMA01zkLTUBVxuJndj)
    password: ENC(MtYJ0nbROLR51kSuPFyMZgD+2Op8Vyir)

file:
  upload:
    path: /data/nfs/file
log:
  upload:
    path: /data/nfs/log

##Actuator
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, metrics
  endpoint:
    health:
      probes:
        enabled: true
    prometheus:
      access: read_only
    metrics:
      access: read_only
  metrics:
    tags:
      application: ${spring.application.name}
  atlas:
    metrics:
      export:
        enabled: false